# Generated by Django 3.2 on 2021-08-02 17:25

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('autor', models.CharField(max_length=100, null=True)),
                ('palabras_clave', models.CharField(max_length=200, null=True)),
                ('pub_fecha', models.DateField(null=True)),
                ('resumen', models.TextField(null=True)),
                ('contenido', models.TextField(null=True)),
                ('art_archivo', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='articulos/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(default='media/anonimo.png', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\user\\Downloads\\Backend2-20210802T163132Z-001\\Backend2\\media'), upload_to='media/')),
                ('genero', models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=1, null=True, verbose_name='Genero')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Descripcion de bigrafia')),
                ('fecNacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('rol', models.CharField(choices=[('a', 'Administrador'), ('u', 'Usuario'), ('e', 'Especialista')], default='u', max_length=1, verbose_name='Rol')),
                ('estatus', models.CharField(choices=[('f', 'Usuario destacado'), ('c', 'Creador de contenido'), ('u', 'Usuario nuevo')], default='u', max_length=1, verbose_name='Estatus')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Direccion')),
                ('url_website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Web Site')),
                ('url_twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('url_instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('url_facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('data_modificada', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios_publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(null=True)),
                ('fecha_publicacion', models.DateField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.articulos')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.perfiles')),
            ],
        ),
        migrations.AddField(
            model_name='articulos',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cuentas.categorias'),
        ),
    ]
